name: Taiwan Number One
favicon: null
layout_spectrum: 0
typography_spectrum: 0.0779284609016031
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c6e5f4'
    - '#68bdde'
    - '#524c2c'
    - '#9e936a'
  brandStrength: 0.5
  lightness: 0.7557612846139818
  saturation: 0.9118311691563576
  rhythmicContrast: 1
purpose: []
